baseURL = "https://theoriginaljuicyjuice.netlify.app"
defaultContentLanguage = "en"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "dream"
googleAnalytics = "G-Y43DYL2ML9"

[params]
    background = "#fff"
    linkColor = "seagreen"

    # dark mode
    # defaultDark = true
    backgroundDark = "#333"
    darkLinkColor = "darkseagreen"
    # darkNav = true
    # dark404 = true

    # images = [""]

    author = "Juice"
    description = "TheOriginalJuicyJuice"
    avatar = "/img/avatar.png"
    headerTitle = "TheOriginalJuicyJuice"
    motto = "Blog"
    
    #social
    rss = true
    email = "TheOriginalJuicyJuice@gmail.com"
    linkedin = "justin-espiritu-b4a277138"
    github = "JuicyJuice1100"
    youtube = "UCraorLjTst3o7EvuauTSoFQ"
    twitch = "theoriginaljuicyjuice"

    siteStartYear = 2021

    #search
    enableSearch = true

    highlightjs = true
    # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
    highlightjsExtraLanguages = ["clojure", "ocaml"]
    highlightjsTheme = "tomorrow"
    highlightjsThemeDark = "tomorrow-night"

    #options
    showSummaryCoverInPost = true
    # hasTwitterEmbed = true
    # reversePostAndAside = true
    # shareInAside = true
    fixedNav = true
    # collapsibleTags = true
    # collapseBySummary = true

[outputs]
  home = ["HTML", "RSS", "JSON"]